org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
forge_version=26.3-66.0.2
forge_version_range=[66,)

mod_id=spawnerplacer
mod_name=Spawner Placer
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.rmrin.spawnerplacer
mod_authors=rmrin
mod_description=Adds a craftable item that places vanilla mob spawners in game.
